In [41]:
import numpy as np
import matplotlib.pyplot as plt

A = np.array([1,2,3])  # np.array([1,2,3.14]) 원소 하나라도 실수면 float으로 바꿔줌 -> (dtype('float64'), (3,))
A.dtype, A.shape

(dtype('int32'), (3,))

In [43]:
np.random.rand(2,2)

array([[0.70190214, 0.04358867],
       [0.94016009, 0.94164998]])

In [ ]:
A = np.random.rand(5,5)
A[2,2] = 1
A[:,4] = 5
A

array([[0.57170765, 0.43133262, 0.74097729, 0.160361  , 5.        ],
       [0.22843606, 0.79998498, 0.21967255, 0.66613687, 5.        ],
       [0.27090875, 0.547107  , 1.        , 0.50440383, 5.        ],
       [0.79929199, 0.513598  , 0.23965245, 0.12842902, 5.        ],
       [0.45649949, 0.3349338 , 0.64687547, 0.46781542, 5.        ]])

In [ ]:
def f(x): # 주소를 복사
    x[0] = 5

l = [1,2,3]
f(l)
l

[5, 2, 3]

In [ ]:
def f(x): # 값 복사
    x = x + 5

l = 5
f(l)
l

5

In [ ]:
def f(x): # 원본 변경 안 됨
    x[0] = 5

l = [1,2,3]
f(l[:])
l

[1, 2, 3]

In [51]:
A = np.arange(1,11)
idx = [1,5,9]
A, A[idx]

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), array([ 2,  6, 10]))